version: '3'

services:
  ethan-keycloak:
    container_name: ethan-keycloak
    image: bitnami/keycloak
    environment:
      - KEYCLOAK_ADMIN_USER=${KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASS}
      - KEYCLOAK_DATABASE_HOST=ethan-keycloak-database
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_USER=keycloak
      - KEYCLOAK_DATABASE_PASSWORD=P@@8@X5gSN!dYka
    # ports:
    #   - 8007:8080
    restart: unless-stopped

  ethan-keycloak-database:
    container_name: ethan-keycloak-database
    image: postgres
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=P@@8@X5gSN!dYka
      - POSTGRES_DB=keycloak
    volumes:
      - /home/ethan/data/keycloak_postgres:/var/lib/postgresql/data
    restart: unless-stopped
 
  ethan-keycloak-swag:
    container_name: ethan-keycloak-swag
    image: lscr.io/linuxserver/swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=ethan-keycloak.duckdns.org
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNSTOKEN}
      - STAGING=false
    volumes:
      - /home/ethan/data/keycloak-swag:/config
      - ./swag-default.conf:/config/nginx/site-confs/default.conf
    ports:
    - 0.0.0.0:10007:443
    restart: unless-stopped
