version: '3'

services:
  keycloak:
    container_name: keycloak
    image: bitnami/keycloak
    environment:
      - KEYCLOAK_ADMIN_USER=${KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASS}
      - KEYCLOAK_DATABASE_HOST=postgres
      - KEYCLOAK_DATABASE_NAME=${POSTGRESQL_DB}
      - KEYCLOAK_DATABASE_USER=${POSTGRESQL_USER}
      - KEYCLOAK_DATABASE_PASSWORD=${POSTGRESQL_PASS}
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - local-keycloak

  postgres:
    container_name: keycloak_db
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASS}
      - POSTGRES_DB=${POSTGRESQL_DB}
    volumes:
      - /tmp/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - local-keycloak

networks:
  local-keycloak:
    name: local-keycloak
    driver: bridge
