name: Update Keycloak
env:
  DUCKDNSTOKEN: ${{ secrets.DUCKDNSTOKEN }}
  KEYCLOAK_ADMIN_USER: ${{ secrets.KEYCLOAK_ADMIN_USER }}
  KEYCLOAK_ADMIN_PASSWORD: ${{ secrets.KEYCLOAK_ADMIN_PASS }}
on: [push, workflow_dispatch]
jobs:
  deploy-application:
    runs-on: [ self-hosted ]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: redeploy application
        run: |
          cd keycloak

          docker compose pull
          docker compose build
          docker compose down
          docker compose up -d
